### PR TITLE
Update Events Listing (closes #11)

### LINKED ISSUE #11: Add Event Info Session 2021
- Move Android Study Jam 2 to Past event Section
- Add Info Session 2021 in upcoming Section

### PR DESCRIPTION
**Pull request by aniket-kr**
This commit achieves the following:
[1] Move Android Study Jam 2 to past events
[2] Add Info Session to Upcoming Events

### CODE REVIEW

**Comment by AdityaBirangal** [comment]
@aniket-kr 
Please add 'Info Session' at First Place.

Sequence will be like Info session , Flutter Bootcamp, Android Study Jam 3

**Review by AdityaBirangal — CHANGES_REQUESTED** [review]
@aniket-kr 
add details of info session 2021 (not 2020)

**Comment by aniket-kr** [comment]
@AdityaBirangal
I can change the order and the details, but what about the date/time on the poster? I haven't found one for 2021 in the assets folder.

**Comment by aniket-kr** [comment]
I have made the suggested changes and I got the poster from marketing mails. Please check.
1. Upcoming events have been ordered by date in descending.
2. Added asset `InfoSession2021.png`.
3. Updated details and poster for `Info Session 2021`.

Please check.

**Review by AdityaBirangal — APPROVED** [review]

**Comment by AdityaBirangal** [comment]
Good work Aniket
Thanks for contributing :)

**Pull request merged**
